### ISSUE TITLE
Problema de Travis con los test Ant

### ISSUE THREAD

**Issue by adrianleira** [adrianleira/VVS2016#2]
No se qué ocurre con los test de Ant y travis.

¿Alguna solución?

**Comment by lauramcastro** [comment]
El mensaje clave en la traza de error es el que os dice: "`[javac] javac: invalid target release: 1.8`".

Según podéis leer en la [documentación de Travis para proyectos en Java](https://docs.travis-ci.com/user/languages/java#Projects-Using-Ant), el compilador usado por defecto es Oracle JDK7. El `build.xml` que estáis usando, generado por NetBeans imagino, es un tanto inmanejable (y os obliga a tener la carpeta `nbproject` en el repositorio, algo bastante feo, pero bueno...), pero debéis revisarlo porque seguramente se fuerza la versión del compilador (o del código fuente) a Java 8 y de ahí el problema.

Alternativamente, podéis [indicarle a Travis-CI que use el Oracle JDK 8 para construir vuestro proyecto](https://docs.travis-ci.com/user/languages/java#Testing-Against-Multiple-JDKs).

**Comment by lauramcastro** [comment]
Ahora que lo habéis resuelto, podéis cerrar esta _issue_! :+1:

**Comment by adrianleira** [comment]
Toda la razón.

**Comment by lauramcastro** [comment]
En las próximas issues a partir de ahora, recordad asignarles etiqueta(s) y también una persona responsable (`Assignee` -normalmente la persona que la cierra-).

**Comment by adrianleira** [comment]
Vale perfecto, lo tendremos en cuenta.
